### ISSUE TITLE
Error installing disco app

### ISSUE THREAD

**Issue by alansill** [googleapis/gnostic#116] opened 2019-04-09 18:13 UTC
Trying out the disco app insallation fails as follows:

```
$ go install github.com/googleapis/gnostic/apps/disco
# github.com/googleapis/gnostic/apps/disco
../../../../../go/src/github.com/googleapis/gnostic/apps/disco/openapiv2.go:41:39: too few values in &openapi_v2.TypeItem literal
```

**Comment by timburks** [comment] 2019-08-15 21:31
Thanks! This was caused by changes in the generated protobuf code.

It should be fixed now in the latest version.

**Closed by timburks** 2019-08-15 21:31 UTC
